stages:
  - docker
  - checkout
  - test

variables:
  BITBAKE_IMAGE: ${METAUPDATER_REGISTRY_IMAGE}:ci-master-bitbake
  BITBAKE_CHECKOUT_IMAGE: ${METAUPDATER_REGISTRY_IMAGE}:ci-master-checkout

include:
  - project: 'olp/edge/ota/connect/client/meta-updater'
    ref: 'master'
    file: 'scripts/ci/gitlab/docker.yml'
  - project: 'olp/edge/ota/connect/client/meta-updater'
    ref: 'master'
    file: 'scripts/ci/gitlab/checkout.yml'
  - project: 'olp/edge/ota/connect/client/meta-updater'
    ref: 'master'
    file: 'scripts/ci/gitlab/tests.yml'

Docker setup:
  extends: .bb_docker_remote

  stage: docker
  except:
    - pushes

Checkout:
  extends: .bb_checkout

  stage: checkout
  variables:
    MANIFEST: thud
    CURRENT_PROJECT: meta-updater-minnowboard
  except:
    - pushes

Build core-image-minimal (minnowboard):
  extends: .bitbake

  stage: test
  variables:
    TEST_BUILD_DIR: 'build-core-image-minimal-minnowboard'
    BITBAKE_TARGETS: 'core-image-minimal'
    TEST_MACHINE: 'intel-corei7-64'
  except:
    - pushes

Oe-selftest minnowboard:
  extends: .oe-selftest

  stage: test
  variables:
    TEST_BUILD_DIR: 'build-oe-minnowboard'
    OE_SELFTESTS: 'updater_minnowboard'
    TEST_MACHINE: 'intel-corei7-64'
  except:
    - pushes
